### ISSUE TITLE
[Feat] Add data-model for send FE

### ISSUE THREAD

**Issue by gunyu1019** [gunyu1019/notion_based_blog_backend#3]
## Describe the new feature<br/>
Add a data model for send Front-End

## TODO<br/>
- [x] Add `post` data model (this model includes content)
- [x] Add `post-item` data model
- [x] Add styled-text data model
- [x] Check all data-model, we needed.
